#!/bin/bash
# Force browser hard refresh untuk load dashboard.js yang sudah dipatch

echo "✅ FIX APPLIED - WebSocket Update"
echo ""
echo "PERUBAHAN:"
echo "- Active Orders di menu Orders: update 100ms (realtime)"
echo "- P&L Stream di Overview: update 800ms (debounced)"
echo ""
echo "CARA TEST:"
echo "1. Buka dashboard: http://YOUR_IP:8080"
echo "2. Hard refresh browser: Ctrl+Shift+R (Chrome/Firefox) atau Cmd+Shift+R (Mac)"
echo "3. Buka menu Orders > Active Orders"
echo "4. Buka menu Overview > P&L Stream"
echo "5. Biarkan WebSocket jalan, cek update realtime"
echo ""
echo "VERIFIKASI:"
echo "- Active Orders harus update smooth tiap 100ms"
echo "- P&L Stream harus update tiap 800ms"
echo "- Tidak ada lag atau delay terlambat"
echo ""
echo "Dashboard sudah jalan di: http://localhost:8080"
